/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { ParkingSlots } from '../Models/ParkingSlotsModel';

export class ParkingSlotsService {
  private static readonly dataSourceName = 'parkingslots';

  public static async create(record: Omit<ParkingSlots, 'ID'>): Promise<IOperationResult<ParkingSlots>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<ParkingSlots, 'ID'>, ParkingSlots>(
      ParkingSlotsService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<ParkingSlots, 'ID'>>): Promise<IOperationResult<ParkingSlots>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<ParkingSlots, 'ID'>>, ParkingSlots>(
      ParkingSlotsService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(ParkingSlotsService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<ParkingSlots>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<ParkingSlots>(
      ParkingSlotsService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<ParkingSlots[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<ParkingSlots>(
      ParkingSlotsService.dataSourceName,
      options
    );
    return result;
  }
}
