/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { PicoyPlaca } from '../Models/PicoyPlacaModel';

export class PicoyPlacaService {
  private static readonly dataSourceName = 'pico y placa';

  public static async create(record: Omit<PicoyPlaca, 'ID'>): Promise<IOperationResult<PicoyPlaca>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<PicoyPlaca, 'ID'>, PicoyPlaca>(
      PicoyPlacaService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<PicoyPlaca, 'ID'>>): Promise<IOperationResult<PicoyPlaca>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<PicoyPlaca, 'ID'>>, PicoyPlaca>(
      PicoyPlacaService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(PicoyPlacaService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<PicoyPlaca>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<PicoyPlaca>(
      PicoyPlacaService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<PicoyPlaca[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<PicoyPlaca>(
      PicoyPlacaService.dataSourceName,
      options
    );
    return result;
  }
}
