/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getPowerSdkInstance } from '@pa-client/power-code-sdk/lib/';
import { dataSourcesInfo } from '../../.power/appschemas/dataSourcesInfo';
import type { IOperationResult } from '@pa-client/power-code-sdk/lib/';
import type { IGetOptions, IGetAllOptions } from '../Models/CommonModels';
import type { Usuarios } from '../Models/UsuariosModel';

export class UsuariosService {
  private static readonly dataSourceName = 'usuarios';

  public static async create(record: Omit<Usuarios, 'ID'>): Promise<IOperationResult<Usuarios>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.createRecordAsync<Omit<Usuarios, 'ID'>, Usuarios>(
      UsuariosService.dataSourceName,
      record
    );
    return result;
  }

  public static async update(id: string, changedFields: Partial<Omit<Usuarios, 'ID'>>): Promise<IOperationResult<Usuarios>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.updateRecordAsync<Partial<Omit<Usuarios, 'ID'>>, Usuarios>(
      UsuariosService.dataSourceName,
      id.toString(),
      changedFields
    );
    return result;
  }

  public static async delete(id: string): Promise<void> {
    await getPowerSdkInstance(dataSourcesInfo).Data.deleteRecordAsync(UsuariosService.dataSourceName, id.toString());
  }

  public static async get(id: string, options?: IGetOptions): Promise<IOperationResult<Usuarios>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveRecordAsync<Usuarios>(
      UsuariosService.dataSourceName,
      id.toString(),
      options
    );
    return result;
  }

  public static async getAll(options?: IGetAllOptions): Promise<IOperationResult<Usuarios[]>> {
    const result = await getPowerSdkInstance(dataSourcesInfo).Data.retrieveMultipleRecordsAsync<Usuarios>(
      UsuariosService.dataSourceName,
      options
    );
    return result;
  }
}
